--- 
filebeat.config.modules: 
  path: "${path.config}/modules.d/*.yml"
  reload.enabled: false
filebeat.inputs: 
  - 
    enabled: true
    paths: 
      - /home/dataflow/devops.json
    type: log
output.logstash: 
  hosts: 
    - "localhost:5060"
processors: 
  - 
    add_host_metadata: ~
  - 
    add_cloud_metadata: ~
setup.kibana: ~
setup.template.settings: 
  index.number_of_shards: 1

